# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Brandy Murray
description: Thank you for visiting my website, I started my career off in finance but always wished I knew more about data analysis and how I could answer the question, "Why". This is when I decided to roll up my sleeves to earn my Master's degree in Business Data Analytics. Throughout my experience, I have developed a strong influential voice that leads with empathy and passion. Below you will find my portfolio which focuses on interesting projects I've recently undertaken, with a strong emphasis on business impact.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: <font size=3> FINANCE DIRECTOR | DATA SCIENCE | MACHINE LEARNING </font>
location: "Helena, MT"
resume_url: /docs/BrandyMurrayResume.pdf
avatar_image: /img/HeadShot.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/brandyemurray" # Add your linkedln handle
github: "https://github.com/brandyemurray"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

